server:
  port: 8083

spring:
  application:
    name: board-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_board_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8  #GRANT ALL PRIVILEGES ON db_board_service* TO jh@localhost;
    username: jh
    password: 1234
  thymeleaf:
    cache: false

jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  open-in-view: false
  show-sql: true
  hibernate:
    ddl-auto: create